### ISSUE TITLE
user-notify: implementation

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#67] opened 2023-06-16 15:24 UTC
Implement user notification via email when requested custom raster product is ready for download

A/C: Demonstrate user get an email notification to download when products are generated

**Comment by joshgarde** [comment] 2023-07-08 01:39
Duplicate of https://github.com/podaac/swodlr/issues/67

**Closed by joshgarde** 2023-07-08 01:39 UTC

**Comment by viviant100** [comment] 2023-07-08 14:53
duplication of https://github.com/podaac/swodlr/issues/59.
